version: "3.9"
services:
  console-db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=bmp
    ports:
      - "5443:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "bmp", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 5